export const copy = {
  es: {
    navProjects: 'Proyectos',
    navAbout: 'Sobre mí',
    navWork: 'Trabajemos',
    skipLink: 'Saltar al contenido',
    heroFirst: 'Ideas claras.',
    heroSecond: 'Productos reales.',
    heroIntro: 'Soy Xavier. Conecto producto, negocio e IA para convertir problemas reales en aplicaciones que se pueden usar.',
    viewProjects: 'Ver proyectos',
    letsTalk: 'Hablemos',
    heroMeta: 'Producto · IA · Desarrollo',
    location: 'Barcelona ↔ En remoto',
    projectLabel: '(01 — PROYECTOS)',
    projectHeading: 'Menos discurso.',
    projectHeadingEm: 'Más producto.',
    projectIntro: 'Una selección de apps propias: problemas que me interesan, decisiones que he tomado y productos que estoy construyendo.',
    caseLink: 'Ver caso',
    archiveTitle: 'También en mi mesa de trabajo',
    archiveIntro: 'Experimentos y proyectos en marcha para probar ideas, explorar herramientas y seguir aprendiendo.',
    aboutLabel: '(02 — SOBRE MÍ)',
    aboutHeading: 'Pienso en producto.',
    aboutHeadingEm: 'Me gusta construirlo.',
    aboutLead: 'Llevo más de diez años entre clientes, negocio y equipos técnicos.',
    aboutBody: 'Hoy gestiono proyectos en Emburse. En paralelo, construyo mis propias apps con IA.',
    now: 'Actualidad',
    strengths: [
      {
        title: 'Entender el problema',
        body: 'Escuchar al cliente y convertir necesidades en decisiones de producto.',
      },
      {
        title: 'Conectar las piezas',
        body: 'Negocio, experiencia de usuario y equipos técnicos en la misma dirección.',
      },
      {
        title: 'Construir para aprender',
        body: 'Prototipos y aplicaciones con IA para probar las ideas sobre algo real.',
      },
      {
        title: 'Llevarlo hasta el final',
        body: 'Priorizar, coordinar, probar y lanzar. Cuidar también lo que pasa después.',
      },
    ],
    workLabel: '(03 — TRABAJEMOS)',
    workHeading: '¿Qué podemos',
    workHeadingEm: 'construir juntos?',
    teamTitle: 'Para tu equipo',
    teamBody: 'Busco mi siguiente reto como AI Product Manager o Technical Product Manager: cerca de los usuarios, de las decisiones y de la construcción del producto.',
    freelanceTitle: 'Para tu proyecto',
    freelanceBody: 'Si tienes un problema concreto, podemos darle forma y construir una primera solución: un MVP, una app o una automatización que te quite trabajo.',
    services: ['Definición de producto y MVP', 'Prototipos y aplicaciones', 'Automatización de procesos'],
    copyEmail: 'Copiar email',
    copiedEmail: 'Email copiado',
    copyFailed: 'Escríbeme a xzanuy@gmail.com',
    closeCase: 'Cerrar caso',
    caseStack: 'Tecnología',
    caseLinks: 'Explorar el proyecto',
    footerNote: 'Hecho con intención.',
    contactSubject: 'Construyamos algo juntos',
    backToTop: 'Volver arriba',
  },
  en: {
    navProjects: 'Projects',
    navAbout: 'About',
    navWork: 'Work with me',
    skipLink: 'Skip to content',
    heroFirst: 'Clear ideas.',
    heroSecond: 'Real products.',
    heroIntro: 'I’m Xavier. I bring product, business and AI together to turn real problems into apps people can use.',
    viewProjects: 'View projects',
    letsTalk: 'Let’s talk',
    heroMeta: 'Product · AI · Development',
    location: 'Barcelona ↔ Remote',
    projectLabel: '(01 — PROJECTS)',
    projectHeading: 'Less talk.',
    projectHeadingEm: 'More product.',
    projectIntro: 'A selection of my own apps: problems I care about, decisions I’ve made and products I’m building.',
    caseLink: 'View case study',
    archiveTitle: 'Also on my workbench',
    archiveIntro: 'Experiments and work in progress to test ideas, explore tools and keep learning.',
    aboutLabel: '(02 — ABOUT)',
    aboutHeading: 'I think in products.',
    aboutHeadingEm: 'I like building them.',
    aboutLead: 'I’ve spent more than ten years working across clients, business and technical teams.',
    aboutBody: 'Today I manage projects at Emburse. Alongside that, I build my own apps with AI.',
    now: 'Currently',
    strengths: [
      {
        title: 'Understand the problem',
        body: 'Listen to customers and turn their needs into product decisions.',
      },
      {
        title: 'Connect the pieces',
        body: 'Bring business, user experience and technical teams into alignment.',
      },
      {
        title: 'Build to learn',
        body: 'Build prototypes and apps with AI to test ideas against something real.',
      },
      {
        title: 'See it through',
        body: 'Prioritise, coordinate, test and launch. Pay attention to what comes next, too.',
      },
    ],
    workLabel: '(03 — WORK TOGETHER)',
    workHeading: 'What could we',
    workHeadingEm: 'build together?',
    teamTitle: 'For your team',
    teamBody: 'I’m looking for my next challenge as an AI Product Manager or Technical Product Manager, working closely with users and taking an active part in product decisions and delivery.',
    freelanceTitle: 'For your project',
    freelanceBody: 'Have a specific problem to solve? We can shape it into a first working solution: an MVP, an app or an automation that takes work off your plate.',
    services: ['Product and MVP definition', 'Prototypes and applications', 'Process automation'],
    copyEmail: 'Copy email',
    copiedEmail: 'Email copied',
    copyFailed: 'Email me at xzanuy@gmail.com',
    closeCase: 'Close case study',
    caseStack: 'Technology',
    caseLinks: 'Explore the project',
    footerNote: 'Made with intention.',
    contactSubject: 'Let’s build something together',
    backToTop: 'Back to top',
  },
};
